### ISSUE TITLE
nes game file running problem 

### ISSUE THREAD

**Issue by Jnickcai** [NJU-ProjectN/LiteNES#4]
1.The nes simulator I use under the windos can run properly, but it can't run after linux compile. Can you give a running nes file.（Invalid or unsupported rom.）
2. In the source code mmc_id why need to =0 or 3 to continue to execute?
  if (mmc_id == 0 || mmc_id == 3 ) {
        // if there is only one PRG block, we must repeat it twice
        if (fce_rom_header.prg_block_count == 1) {
            mmc_copy(0x8000, buf, 0x4000);
            mmc_copy(0xC000, buf, 0x4000);
        }
        else {
            mmc_copy(0x8000, buf, 0x8000);
        }
    }

**Comment by jiangyy** [comment]
LiteNES lacks many functions on its simple nature (and is no longer maintained). Try simple roms like Super Mario Bros.
